"""Scores every account in the book live and groups whichever ones need
action right now by play — the plays-first dashboard's primary view. Real,
countable data throughout: no fabricated trend statistics, no cluster
invented after the fact.
"""
from datetime import datetime

import db
from pipeline.ad_creative import AD_CREATIVE_VARIANTS
from pipeline.content_generator import signal_opening_preview
from pipeline.knowledge_base import ACTION_TIER_1_LABEL, FUNCTIONAL_AREAS, PLAY_ORDER, PLAYS, SIGNAL_LIBRARY
from pipeline.scorer import score_account


def _play_personas(driving_signals: list) -> list:
    """Every functional area any of this play's driving signals targets,
    deduped, in FUNCTIONAL_AREAS' natural order — the actual persona set
    this play's messaging is written for, not a guess."""
    seen = []
    for signal_type in driving_signals:
        for fa in SIGNAL_LIBRARY.get(signal_type, {}).get("functional_areas", []):
            if fa not in seen:
                seen.append(fa)
    return [FUNCTIONAL_AREAS[fa]["label"] for fa in seen if fa in FUNCTIONAL_AREAS]


def _play_email_hooks(driving_signals: list) -> list:
    """One representative opening line per driving signal, generated by the
    real content-generation logic — a manager can read exactly how each
    signal opens an email without clicking into an account and a contact."""
    return [
        {"signal_label": SIGNAL_LIBRARY[st]["label"], "preview": signal_opening_preview(st)}
        for st in driving_signals if st in SIGNAL_LIBRARY
    ]


def score_all_accounts(today: datetime = None) -> list:
    today = today or datetime.utcnow()
    today_str = today.strftime("%Y-%m-%d")
    results = []
    for account in db.list_accounts():
        raw_signals = db.list_signals_for_account(account["id"])
        engaged = db.engaged_contact_count(account["id"], today_str)
        scored = score_account(account, raw_signals, engaged, today)
        results.append({**account, **scored})
    return results


def accounts_needing_action(today: datetime = None) -> list:
    return [a for a in score_all_accounts(today) if a["tier"] == ACTION_TIER_1_LABEL]


def play_groups(today: datetime = None) -> list:
    today = today or datetime.utcnow()
    needing_action = accounts_needing_action(today)
    total = len(needing_action)
    if total == 0:
        return []

    groups = {}
    for a in needing_action:
        groups.setdefault(a["play"], []).append(a)

    result = []
    for play_key in PLAY_ORDER:
        accounts = groups.get(play_key)
        if not accounts:
            continue
        pdef = PLAYS[play_key]
        known_contacts_total = 0
        for a in accounts:
            contacts = db.list_contacts_for_account(a["id"])
            a["known_contacts"] = sum(1 for c in contacts if c["is_known_contact"])
            known_contacts_total += a["known_contacts"]
        result.append({
            "play": play_key,
            "label": pdef["label"],
            "angle": pdef["angle"],
            "tactical_mix": pdef["tactical_mix"],
            "gifting_allowed": pdef["gifting_allowed"],
            "how_signals_work": pdef["how_signals_work"],
            "connections_required": pdef["connections_required"],
            "launch_explainer": pdef["launch_explainer"],
            "count": len(accounts),
            "pct_of_needing_action": round(100 * len(accounts) / total, 1),
            "accounts": accounts,
            "known_contacts_total": known_contacts_total,
            "personas": _play_personas(pdef["driving_signals"]),
            "email_hooks": _play_email_hooks(pdef["driving_signals"]),
            "ads_involved": pdef.get("ads_involved", False),
            "ad_angle": pdef.get("ad_angle"),
            "ad_creatives": list(AD_CREATIVE_VARIANTS.values()) if pdef.get("ads_involved") else [],
        })
    result.sort(key=lambda p: p["count"], reverse=True)
    return result
